# -*- coding: utf-8 -*-
"""Australia3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eifbOPXANr_EpFMnVYGYbpmGBYHO7hCX

Import Necessory Library
"""

import os
import sys
from google.colab import drive
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
from shapely.geometry import Point
from shapely.geometry import Polygon
from itertools import product
from google.colab import data_table
import numpy as np
import math
from google.colab import files
data_table.enable_dataframe_formatter()

"""Google Drive Connection and Necessary file connection stored in google drive folder."""

drive.mount('/content/drive')
MTanalysis = os.path.join('drive', 'My Drive', 'MTanalysis')
sppVal = pd.read_csv(os.path.join(MTanalysis, 'sppVal.csv'))

"""Upload Stem mapping file"""

stemmapping = files.upload()
df = pd.read_csv('TreeLoc.csv')

"""Upload Boundary polygon shape zip"""

cfouter_shp = files.upload()

"""Read sppVal.csv table inorder to join dataframe with its species value

# Join the GeoDataFrames based on the 'species' column
merged_gdf = df_with_remarks.merge(sppVal, left_on='species', right_on='Scientific Name')
"""

joined_df = df.merge(sppVal, left_on='species', right_on='Scientific Name')

"""copy the joined_df as 'result_df'."""

result_df = joined_df.copy()

"""## Function to perform calculations and add new columns"""

def add_calculated_columns(df):
    df['stem_volume'] = np.exp(df['a'] + df['b'] * np.log(df['dia_cm']) + df['c'] * np.log(df['height_m'])) / 1000
    df['branch_ratio'] = df['dia_cm'].apply(lambda x: 0.1 if x < 10 else 0.2)
    df['branch_volume'] = df['stem_volume'] * df['branch_ratio']
    df['tree_volume'] = df['stem_volume'] + df['branch_volume']
    df['cm10diaratio'] = np.exp(df['a1'] + df['b1'] * np.log(df['dia_cm']))
    df['cm10topvolume'] = df['stem_volume'] * df['cm10diaratio']
    df['gross_volume'] = df['stem_volume'] - df['cm10topvolume']
    df['net_volume'] = df.apply(lambda row: row['gross_volume'] * 0.9 if row['class'] == 'A' else row['gross_volume'] * 0.8, axis=1)
    df['net_volum_cft'] = df['net_volume'] * 35.3147
    df['firewood_m3'] = df['tree_volume'] - df['net_volume']
    df['firewood_chatta'] = df['firewood_m3'] * 0.105944
    return df

"""Apply the function to the dataframe"""

result_df = add_calculated_columns(df=result_df)

columns_to_drop = ['SN', 'Scientific Name', 'a', 'b', 'c', 'a1', 'b1', 's', 'm', 'bg']
result_df = result_df.drop(columns=columns_to_drop)

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=result_df)

result_df

# @title Spatial Distribution of Trees

import matplotlib.pyplot as plt

# Assuming your data is in a pandas DataFrame named 'df'

plt.figure(figsize=(10, 8))
for species in df['species'].unique():
    subset = df[df['species'] == species]
    plt.scatter(subset['X'], subset['Y'], label=species, alpha=0.5)
plt.title('Spatial Distribution of Trees')
plt.xlabel('X Coordinate')
plt.ylabel('Y Coordinate')
_ = plt.legend()

result_df.to_csv('result_df.csv', index=False)
files.download('result_df.csv')